name: AwayTools
version: 1.0
main: pl.awaymc.tools.Main
authors: [Piechuuu, dawidos506]

commands:
  gamemode:
    description: Zmienia tryb gry gracza.
    aliases: [gm]
  broadcast:
    description: Wiadomosc do wszystkich graczy na serwerze.
    aliases: [bc]
  heal:
    description: Leczenie gracza.
  feed:
    description: Nasycenie gracza.